version: '3.1'

services:
  app:
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///workshop.db